[package]
name = "raymarching"
version = "0.1.0"
edition = "2021"

[features]
optimize = ["log/release_max_level_warn"]
default = ["optimize"]

[dependencies]
env_logger = "0.9"
log = "0.4"
pixels = "0.8.0"
winit = "0.25"
winit_input_helper = "0.10"
